# Copyright (c) 2019-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

FROM python:3.9-alpine AS builder

#WORKDIR /home/static
RUN apk update && apk add git

COPY . testpages.adblockplus.org

# Build CMS
RUN git clone https://gitlab.com/eyeo/websites/cms.git
RUN git -C cms checkout fbd1527b9f98d99a8b62c6ad5e32ac7758c19a28
RUN pip3 install -r cms/requirements.txt

# # Generate test pages files
ENV SITE_URL=http://localhost:5001
RUN mkdir -p /var/www/localhost/static
RUN PYTHONPATH=cms python -m cms.bin.generate_static_pages testpages.adblockplus.org /var/www/localhost/static

# Also copy package.json and package-lock.json
COPY package*.json /var/www/localhost
COPY endpoints /var/www/localhost/endpoints

# # Copy the static website
# # Use the .dockerignore file to control what ends up inside the image!
# COPY cms .

FROM node:18-alpine

# Copy the static website
# Use the .dockerignore file to control what ends up inside the image!
COPY --from=builder /var/www/localhost /var/www/localhost

WORKDIR /var/www/localhost

RUN cd /var/www/localhost && npm install --omit=dev
# Run BusyBox httpd
CMD ["npm", "run", "start-endpoints"]
